# Generated by Django 5.2.8 on 2025-11-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('moisture', models.FloatField()),
                ('soil_ph', models.FloatField()),
                ('pest_level', models.FloatField()),
                ('recommendation', models.CharField(max_length=255)),
            ],
        ),
    ]
