# Generated by Django 5.2.8 on 2025-11-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farminput',
            name='recommendation',
            field=models.TextField(),
        ),
    ]
